# Generated by Django 5.1.1 on 2025-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_ingredients_ingredient_rename_recipes_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
