# Generated by Django 5.1.1 on 2025-07-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_favorite_recipe_alter_shoppingcart_recipe_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('follower', 'followed'), name='unique_subscription'),
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('followed')), _negated=True), name='prevent_self_follow'),
        ),
    ]
