# Generated by Django 5.1.1 on 2025-08-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_favorite_options_alter_follower_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['author'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['author'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
