# Generated by Django 5.1.1 on 2025-06-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppinCart',
            new_name='ShoppingCart',
        ),
    ]
