# Generated by Django 5.1.1 on 2025-06-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_follower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
