# Generated by Django 5.1.1 on 2025-07-29 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_cooking_time_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя может содержать только буквы, цифры и @/./+/-/_', regex='^[\\w.@+-]+$')]),
            preserve_default=False,
        ),
    ]
