# Generated by Django 5.1.1 on 2025-07-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_recipe_is_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
